version: '3'
services:
    php:
        build: .
        volumes:
            - '../:/var/www/html'

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - '../:/var/www/html'
            - './vhost.conf:/etc/nginx/conf.d/default.conf'
